### ISSUE TITLE
How do I import ovpn config file?

### ISSUE THREAD

**Issue by MurhafSousli** [smithp1992/telnet-openvpn#3]

**Comment by smithp1992** [comment]
OpenVPN must already be installed on your computer. In order to start a configuration file you must open a command prompt, cd to the configuration file directory, and type `openvpn myconfig.ovpn` where myconfig.ovpn is the name of the OpenVPN configuration file. Note: you must make sure you have the necessary OpenVPN file configuration stated [here](https://github.com/smithp1992/telnet-openvpn#important-ovpn-file-information).

**Comment by MurhafSousli** [comment]
@smithp1992 I have openvpn installed, and the config file from [vpnbook](https://www.vpnbook.com/). But if I need to use the command prompt to connect then how does the library work?

**Comment by smithp1992** [comment]
Make sure the file is .ovpn as that is what I did my tests on. This library is used to send commands to the openvpn management port through telnet. That being said, a management IP and port must be specified in the configuration file or during initialization in order to connect via telnet. As stated above there is a section in the telnet-openvpn documentation which shows what should be added to the configuration file. Once these lines are added then you must run `openvpn myconfig.ovpn` on your configuration file to start the openvpn management port.

**Comment by MurhafSousli** [comment]
@smithp1992 Thanks a lot!
