### ISSUE TITLE
how can i get the process id?

### ISSUE THREAD

**Issue by anshao** [smithp1992/telnet-openvpn#4]
use the event 'data'

but i can't got the process id
{ state:
   [ '1527675255',
     'CONNECTED',
     'SUCCESS',
     '10.8.10.6',
     'xxx.xxx.xx.xx\r' ] }

not found the 'pid' field

**Comment by smithp1992** [comment]
In order to get the process id you must run the command `vpn.exec('pid')` from within your `vpn.on('connect')` event emitter. This will send back the object {pid: 1234} or something similar from the data event emitter. Other OpenVPN management interface commands can be found [here](https://openvpn.net/index.php/open-source/documentation/miscellaneous/management-interface.html). Hope that helps.
